### ISSUE TITLE
Error training controller with rank

### ISSUE THREAD

**Issue by AliBaheri** [AppliedDataSciencePartners/WorldModels#13]
Thanks for sharing this great repo.
I am receiving the following error when I run the controller module.
In fact, the previous suggestion from @davidADSP (in one of the closed issues) did not help me.
Any other suggestion for the following error:

Traceback (most recent call last): File "05_train_controller.py", line 521, in <module> if "parent" == mpi_fork(args.num_worker+1): os.exit() File "05_train_controller.py", line 491, in mpi_fork subprocess.check_call(["mpirun", "-np", str(n), sys.executable] +['-u']+ sys.argv, env=env) File "/usr/lib/python3.6/subprocess.py", line 291, in check_call raise CalledProcessError(retcode, cmd) subprocess.CalledProcessError: Command '['mpirun', '-np', '2', '/home/baheri/.virtualenvs/worldmodels/bin/python', '-u', '05_train_controller.py', 'car_racing', '--num_worker', '1', '--num_worker_trial', '1', '--num_episode', '4', '--max_length', '1000', '--eval_steps', '25']' returned non-zero exit status 1.

Thanks.

**Comment by waiyc** [comment]
@AliBaheri did you managed to solve this error? I can only train the controller without using GPU which is pretty slow in terms of training time.

**Comment by davidADSP** [comment]
I have updated the codebase to run with TF2.2 - could you retry with the new codebase?
