### ISSUE TITLE
Error training controller

### ISSUE THREAD

**Issue by boucher** [AppliedDataSciencePartners/WorldModels#3]
```boucher@boucher-pc ~/Projects/WorldModels $ python 05_train_controller.py car_racing --num_worker 1 --num_worker_trial 2 --num_episode 16 --max_length 1000 --eval_steps 25
/home/boucher/.virtualenvs/worldmodels/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
['mpirun', '-np', '2', '/home/boucher/.virtualenvs/worldmodels/bin/python', '05_train_controller.py', 'car_racing', '--num_worker', '1', '--num_worker_trial', '2', '--num_episode', '16', '--max_length', '1000', '--eval_steps', '25']
/home/boucher/.virtualenvs/worldmodels/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/home/boucher/.virtualenvs/worldmodels/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Using TensorFlow backend.
assigning the rank and nworkers 1 0
assigning the rank and nworkers 1 0
2018-04-18 18:30:08.922363: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-04-18 18:30:08.927218: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-04-18 18:30:09.084787: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-04-18 18:30:09.085010: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1344] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.683
pciBusID: 0000:01:00.0
totalMemory: 10.91GiB freeMemory: 9.47GiB
2018-04-18 18:30:09.085020: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1423] Adding visible gpu devices: 0
2018-04-18 18:30:09.085433: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-04-18 18:30:09.085774: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1344] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.683
pciBusID: 0000:01:00.0
totalMemory: 10.91GiB freeMemory: 9.47GiB
2018-04-18 18:30:09.085783: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1423] Adding visible gpu devices: 0
2018-04-18 18:30:09.224535: I tensorflow/core/common_runtime/gpu/gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-04-18 18:30:09.224562: I tensorflow/core/common_runtime/gpu/gpu_device.cc:917]      0 
2018-04-18 18:30:09.224566: I tensorflow/core/common_runtime/gpu/gpu_device.cc:930] 0:   N 
2018-04-18 18:30:09.224701: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9110 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
2018-04-18 18:30:09.228563: I tensorflow/core/common_runtime/gpu/gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-04-18 18:30:09.228578: I tensorflow/core/common_runtime/gpu/gpu_device.cc:917]      0 
2018-04-18 18:30:09.228597: I tensorflow/core/common_runtime/gpu/gpu_device.cc:930] 0:   N 
2018-04-18 18:30:09.229018: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 253 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
size of model 867
size of model 867
(1,2mirr1)-aCMA-ES (mu_w=1.0,w_1=100%) in dimension 867 (seed=205998, Wed Apr 18 18:30:09 2018)
('process', 0, 'out of total ', 1, 'started')
('training', 'car_racing')
('population', 2)
('num_worker', 1)
('num_worker_trial', 2)
('num_episode', 16)
('max_length', 1000)
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
Traceback (most recent call last):
  File "05_train_controller.py", line 461, in <module>
    main(args)
  File "05_train_controller.py", line 410, in main
    master()
  File "05_train_controller.py", line 319, in master
    send_packets_to_slaves(packet_list)
  File "05_train_controller.py", line 233, in send_packets_to_slaves
    assert len(packet_list) == num_worker-1
AssertionError
(1,2mirr1)-aCMA-ES (mu_w=1.0,w_1=100%) in dimension 867 (seed=250130, Wed Apr 18 18:30:09 2018)
('process', 0, 'out of total ', 1, 'started')
('training', 'car_racing')
('population', 2)
('num_worker', 1)
('num_worker_trial', 2)
('num_episode', 16)
('max_length', 1000)
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
Traceback (most recent call last):
  File "05_train_controller.py", line 461, in <module>
    main(args)
  File "05_train_controller.py", line 410, in main
    master()
  File "05_train_controller.py", line 319, in master
    send_packets_to_slaves(packet_list)
  File "05_train_controller.py", line 233, in send_packets_to_slaves
    assert len(packet_list) == num_worker-1
AssertionError
Traceback (most recent call last):
  File "05_train_controller.py", line 460, in <module>
    if "parent" == mpi_fork(args.num_worker+1): os.exit()
  File "05_train_controller.py", line 429, in mpi_fork
    subprocess.check_call(["mpirun", "-np", str(n), sys.executable] +['-u']+ sys.argv, env=env)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['mpirun', '-np', '2', '/home/boucher/.virtualenvs/worldmodels/bin/python', '-u', '05_train_controller.py', 'car_racing', '--num_worker', '1', '--num_worker_trial', '2', '--num_episode', '16', '--max_length', '1000', '--eval_steps', '25']' returned non-zero exit status 1
```

Not exactly sure what the problem is here. I had to lower the number of workers to run on my gpu without running out of memory, but playing around with that number and the num_worker_trial I wasn't able to get it past this error.

**Comment by boucher** [comment]
If I disable that assertion I end up getting this error:
```
mpi4py.MPI.Exception: MPI_ERR_RANK: invalid rank
Traceback (most recent call last):
  File "05_train_controller.py", line 461, in <module>
    if "parent" == mpi_fork(args.num_worker+1): os.exit()
  File "05_train_controller.py", line 430, in mpi_fork
    subprocess.check_call(["mpirun", "-np", str(n), sys.executable] +['-u']+ sys.argv, env=env)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['mpirun', '-np', '2', '/home/boucher/.virtualenvs/worldmodels/bin/python', '-u', '05_train_controller.py', 'car_racing', '--num_worker', '1', '--num_worker_trial', '2', '--num_episode', '16', '--max_length', '1000', '--eval_steps', '25']' returned non-zero exit status 1
```

Similarly, reverting to tensorflow on the cpu fails with the given invocation

**Comment by davidADSP** [comment]
It's probably related to this:
https://gist.github.com/ozooxo/9280304

It's already wrong by this point:

```
assigning the rank and nworkers 1 0
assigning the rank and nworkers 1 0
```

This should read (for 1 slave, 1 master - as per your setup)
```
assigning the rank and nworkers 2 1
assigning the rank and nworkers 2 0
```

So for some reason `comm.Get_size()` always returns 1
and `comm.Get_rank()` returns 0 on your machine, hence the error.

Try the fix in the above post and see if that helps.

**Comment by boucher** [comment]
Thanks, just went out of town, will test it out when I get back.

**Comment by boucher** [comment]
hmm, i only seem to have one version of mpi (libmpich12), is there a version i should be running for this to work?

**Comment by boucher** [comment]
Ok, I was looking in the wrong place. I've gotten further and am now stuck on an out of memory error, so I'll work on that for a while and close this issue.

**Comment by davidADSP** [comment]
Let me know if the memory error persists - I fixed a bug on this a while back so ensure you have the latest version of the repo

**Comment by boucher** [comment]
Thanks, I was able to get it running, but the box2d simulation runs *extremely* slowly, is that normal? I left it running overnight and it's still going; the actual rendering on screen is like 1 frame every 10 seconds.

**Comment by CompilerBian** [comment]
I have reduced the worker number to 1 and the worker_trial number to 2 (which is the minimum number that I can set). But I still got the out of memory error, even if I used 4 Titan X GPUs, could you tell me how to fix the memory error?

**Comment by C351** [comment]
Run `watch -n 1 nvidia-smi` and see if memory is still being used after error. 
If it is run `pkill -9 python` and try again, 
Seems like when it errors out python stays open so gpu memory stays full

**Comment by AliBaheri** [comment]
@boucher 
I am receiving the same error as yours. Did you resolve the issue?
In fact, the suggestion from @davidADSP did not help me.
Any other suggestion for the following error:

`Traceback (most recent call last):
  File "05_train_controller.py", line 521, in <module>
    if "parent" == mpi_fork(args.num_worker+1): os.exit()
  File "05_train_controller.py", line 491, in mpi_fork
    subprocess.check_call(["mpirun", "-np", str(n), sys.executable] +['-u']+ sys.argv, env=env)
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['mpirun', '-np', '2', '/home/baheri/.virtualenvs/worldmodels/bin/python', '-u', '05_train_controller.py', 'car_racing', '--num_worker', '1', '--num_worker_trial', '1', '--num_episode', '4', '--max_length', '1000', '--eval_steps', '25']' returned non-zero exit status 1.
`
