### ISSUE TITLE
Error training VAE - input wrong dimension

### ISSUE THREAD

**Issue by tawnkramer** [AppliedDataSciencePartners/WorldModels#6]
I did generate only 2 episodes to do a dry run before committing to all 2000. Perhaps that's the problem.
```
ls -lh data
total 5.5G
-rw-rw-r-- 1 tkramer tkramer 1.4M Apr 23 08:41 action_data_car_racing_0.npy
-rw-rw-r-- 1 tkramer tkramer 1.4M Apr 23 08:57 action_data_car_racing_1.npy
-rw-rw-r-- 1 tkramer tkramer 2.8G Apr 23 08:41 obs_data_car_racing_0.npy
-rw-rw-r-- 1 tkramer tkramer 2.8G Apr 23 08:57 obs_data_car_racing_1.npy
```

trained with: 
python 02_train_vae.py --start_batch 0 --max_batch 1 --new_model

At the end of the first epoch:

48000/48000 [==============================] - 323s 7ms/step - loss: 7.0854 - vae_r_loss: 6.5440 - vae_kl_loss: 0.5414 - val_loss: 3.3674 - val_vae_r_loss: 2.8730 - val_vae_kl_loss: 0.4944
Building batch 1...
Traceback (most recent call last):
  File "02_train_vae.py", line 53, in <module>
    main(args)
  File "02_train_vae.py", line 42, in main
    vae.train(data)
  File "/home/tkramer/projects/WorldModels/vae/arch.py", line 120, in train
    callbacks=callbacks_list)
  File "/home/tkramer/projects/WorldModels/env/lib/python3.5/site-packages/keras/engine/training.py", line 1630, in fit
    batch_size=batch_size)
  File "/home/tkramer/projects/WorldModels/env/lib/python3.5/site-packages/keras/engine/training.py", line 1476, in _standardize_user_data
    exception_prefix='input')
  File "/home/tkramer/projects/WorldModels/env/lib/python3.5/site-packages/keras/engine/training.py", line 113, in _standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected input_1 to have 4 dimensions, but got array with shape (3840000, 64, 3)
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x7f1e1df6f278>>
Traceback (most recent call last):
  File "/home/tkramer/projects/WorldModels/env/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 712, in __del__
  File "/home/tkramer/projects/WorldModels/env/lib/python3.5/site-packages/tensorflow/python/framework/c_api_util.py", line 31, in __init__
TypeError: 'NoneType' object is not callable

**Comment by tawnkramer** [comment]
I think this is because you reshape loaded data with
```
data = np.array([item for obs in data for item in obs])
```
and then concatenate the next batch of new_data to data, which is now a different shape.

one solution is:
```
      train_data = np.array([item for obs in data for item in obs])
      vae.train(train_data)
```
thereby leaving data in it's original form. However, these are quite large and going to consume an additional @8gb for each batch added. Should we just rotate through the batches and dump the old ones?

**Comment by tawnkramer** [comment]
This reshuffles the validation/train set on each additional batch. This is going to over fit, as the previous runs validation is rolled into the train set. Better to increase epochs and use stable train/test val split imo.

**Comment by tawnkramer** [comment]
pull request to fix these. broken up, in case you want only one change or the other.

**Comment by davidADSP** [comment]
Thanks for spotting this - due to recent changes, I forgot to reset first_item after each batch.
This should have the same effect as your pull request.
